# --- 2. Deployment ---
# This manages the lifecycle of your application's pods.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: presigned-url-upload-artifact
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        # IMPORTANT: Replace this with the actual path to your image
        image: ghcr.io/tafy2392/presigned-url-upload-artifact-backend:sha-9f0ad06
        ports:
        - containerPort: 3000
        envFrom:
          # This loads all key-value pairs from the secret as environment variables
          - secretRef:
              name: backend-aws-secrets

---
# --- 3. Service ---
# This exposes your backend pods with a stable network endpoint.
apiVersion: v1
kind: Service
metadata:
  name: namespace: presigned-url-upload-artifact-backend
  namespace: presigned-url-upload-artifact
spec:
  # Use ClusterIP for internal communication within the cluster.
  # If you need to expose this directly to the internet, change to LoadBalancer.
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
