# .github/workflows/publish-to-ghcr.yml

name: Publish Frontend to GHCR 🚀

# This workflow runs on any push to the 'main' branch.
# It can also be triggered manually from the Actions tab.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Define environment variables for the workflow
env:
  # The name of the Docker image. We use the repository owner and a custom name.
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-push:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest
    # Define permissions for the GITHUB_TOKEN
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GITHUB_TOKEN is automatically generated

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
          tags: |
            type=sha
          images: ${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Use the root directory as the build context
          push: true # Actually push the image
          tags: ${{ steps.meta.outputs.tags }} # Use the tags generated by the metadata action
          labels: ${{ steps.meta.outputs.labels }} # Add useful labels to the image
